default: &default
  adapter: postgresql
  encoding: unicode
  
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ichigo_daihuku_development

test:
  <<: *default
  database: ichigo_daihuku_test

production:
  <<: *default
  database: ichigo_daihuku_production
  username: ichigo_daihuku
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>